// ignore_for_file: non_constant_identifier_names

class Students2 {
  String image;
  String name;
  String nickname;
  String dob;
  String state_of_origin;
  int mobile_number;
  String email;
  String linkedIn;
  String instagram;
  String facebook;
  String twitter;
  String position_held;
  String skills;
  String hobbies;
  String favorite_course;
  String class_crush;
  String parting_words;

  Students2(
      {required this.image,
      required this.name,
      required this.nickname,
      required this.dob,
      required this.state_of_origin,
      required this.mobile_number,
      required this.email,
      required this.linkedIn,
      required this.instagram,
      required this.facebook,
      required this.twitter,
      required this.position_held,
      required this.skills,
      required this.hobbies,
      required this.favorite_course,
      required this.class_crush,
      required this.parting_words});
}

List<Students2> studentList2 = [
  Students2(
      image: 'assets/students/13.jpg',
      name: 'Adekola Bolanle Mary ',
      nickname: 'Baams (Rie b)',
      dob: '5/13',
      state_of_origin: 'Ogun',
      mobile_number: 09093105590,
      email: 'adekoladebola7',
      linkedIn: 'Adekola Bolanle',
      instagram: '___baams ',
      facebook: 'Adekola Omobolanle',
      twitter: '-',
      position_held: '-',
      skills: 'Mediation ',
      hobbies:
          'Communicating, exercising, singing and making not perfect moves. ',
      favorite_course: 'Law of contract ',
      class_crush: 'Any fine boy',
      parting_words: 'Dear beautiful people, be kind. '),
  Students2(
      image: 'assets/students/14.jpg',
      name: 'Adekoya Babatunde',
      nickname: 'EDNUT',
      dob: '8/13',
      state_of_origin: 'Ogun',
      mobile_number: 08147908218,
      email: 'tundednut60@gmail.com',
      linkedIn: 'Tunde Ednut',
      instagram: 'Ednut_the_photographer',
      facebook: 'EDNUT ADEKOYA',
      twitter: '_ednut',
      position_held: 'HOD Media and publicity (2018- 2020)',
      skills: 'Photography/social media influencer',
      hobbies: 'Playing table tennis',
      favorite_course: 'Nigeria Legal system',
      class_crush: 'No one',
      parting_words: '-'),
  Students2(
      image: 'assets/students/15.jpg',
      name: 'Adelaja Olamide Oluwatosin ',
      nickname: 'Lam Hephzibah ',
      dob: '6/4',
      state_of_origin: 'Ogun',
      mobile_number: 08111182017,
      email: 'Adelajaolamide7@gmail.com',
      linkedIn: '-',
      instagram: 'Hephmillie_xx',
      facebook: 'Heph Zibah ',
      twitter: '@Hephzibah_lam',
      position_held: 'Best of d Best ',
      skills: 'I love creating Artworks 🖼, drawing ✍️ painting',
      hobbies: 'Football, Music , Food, 4:20, Money 💰 ',
      favorite_course: 'Criminology ',
      class_crush: 'Rather not say',
      parting_words: 'Never Lose Hope coz NHL🧢💯'),
  Students2(
      image: 'assets/students/16.jpg',
      name: 'Adeleke Peter adewale',
      nickname: 'Wale_deleke',
      dob: '11/5',
      state_of_origin: 'Oyo',
      mobile_number: 08109858985,
      email: 'Adelekepeter13@gmail.com',
      linkedIn: 'Adele Peter',
      instagram: 'Wale_Deleke',
      facebook: 'Peter Adeleke',
      twitter: 'Wale_deleke',
      position_held:
          'General secretary for Niyi Akintola chamber Assistant general secretary for intellectual property club,Oou. ',
      skills: 'Researching, ability to work under pressure, negotiating skills',
      hobbies: 'Watching football,listening to music ',
      favorite_course: 'Family law',
      class_crush: '😂😂😂 I no answer boss ',
      parting_words:
          'Well change is the constant thing in life but change itself isn’t constant.'),
  Students2(
      image: 'assets/students/17.jpg',
      name: 'Ademuyiwa Adekolapo Hazeez',
      nickname: 'Kolapo',
      dob: '4/3',
      state_of_origin: 'Ogun',
      mobile_number: 08151309084,
      email: 'ademuyiwaadekolapo@gmail.com',
      linkedIn: '-',
      instagram: 'Ade_kholapo',
      facebook: '-',
      twitter: 'Ade_kholapo',
      position_held: '-',
      skills: 'Play football ',
      hobbies: 'Play football ',
      favorite_course: 'Family law ',
      class_crush: 'Bisola',
      parting_words: '-'),
  Students2(
      image: 'assets/students/18.jpg',
      name: 'Adeniji Anuoluwapo Elizabeth ',
      nickname: 'Mercyluxury',
      dob: '10/16',
      state_of_origin: 'Ogun',
      mobile_number: 07065478578,
      email: 'mercyelizabethblaze@gmail.com',
      linkedIn: '@Mercyelizabeth',
      instagram: '_mercyelizabeth ',
      facebook: 'Adeniji Elizabeth ',
      twitter: 'Mercyelizabeth ',
      position_held: '-',
      skills: 'Business ',
      hobbies: 'Swimming, Going out, Shopping and Discovering New Locations.',
      favorite_course:
          'Women and the law, because it taught me so much about womanhood and it’s rights',
      class_crush: 'Peterclaver in 100level ',
      parting_words:
          'It was a great pleasure to be in the same class as you brilliant folks and I love y’all '),
  /*Students(
      image: 'assets/students/19.jpg',
      name: 'Adenuga Paul',
      nickname: '-',
      dob: '10/30',
      state_of_origin: 'Ogun',
      mobile_number: 07064306722,
      email: 'hadenugapaul@gmail.com',
      linkedIn: '-',
      instagram: 'Paul_adenuga2',
      facebook: '-',
      twitter: '-',
      position_held: '-',
      skills: 'Tech',
      hobbies: 'Tech, gaming and having money ',
      favorite_course: 'Women and the law',
      class_crush: 'Oreoluwa Kendore',
      parting_words: '-'),*/
  Students2(
      image: 'assets/students/20.jpg',
      name: 'Adeola Elizabeth Ayanbanjo ',
      nickname: 'Adey ',
      dob: '2/23',
      state_of_origin: 'Ogun',
      mobile_number: 08109821598,
      email: 'Ayanbanjoelizabeth62@gmail.com',
      linkedIn: 'Adeola Ayanbanjo',
      instagram: 'hardey_horlahr1',
      facebook: 'Ayanbanjo Adeola Elizabeth ',
      twitter: '-',
      position_held:
          'OOUSUG Judicial council Registrar, Clasfon welfare director, Veecee success stories Editor, Veecee success stories Analyst/Vice President ',
      skills: '-',
      hobbies: 'Watching movies, listening to music and traveling ',
      favorite_course:
          'Women and the law. The course is just so relatable and doesn’t require extra.',
      class_crush: 'None',
      parting_words:
          'It’s sad, but sometimes moving on with the rest of your life, starts with goodbye. – Carrie Underwood'),
  Students2(
      image: 'assets/students/21.jpg',
      name: 'Adeosun Favour Oluwakamimayo',
      nickname: 'Fefe of law',
      dob: '6/16',
      state_of_origin: 'Ogun',
      mobile_number: 09035518381,
      email: 'foluwakamimayo10@gmail.com',
      linkedIn: 'Favour Adeosun',
      instagram: 'fe_fe_a',
      facebook: 'Favour Adeosun',
      twitter: 'Fefe',
      position_held:
          'President Veecee Success Stories\nGen.Sec Tax club\nPresident Tax club ',
      skills: 'Writing ',
      hobbies: 'Writing, cooking and meeting people',
      favorite_course: 'Tax law',
      class_crush: 'None',
      parting_words:
          'Whatever your mind can conceive it can achieve, never limit yourself for any reason. '),
  Students2(
      image: 'assets/students/22.jpg',
      name: 'Adeoye Praise Adejoke',
      nickname: 'Joke',
      dob: '7/3',
      state_of_origin: 'Lagos',
      mobile_number: 08024491459,
      email: 'Praiseadejoke@gmail.com',
      linkedIn: '-',
      instagram: 'Titt_up',
      facebook: 'Praise Adeoye',
      twitter: 'Adeoye praise 2',
      position_held: 'Welfare director of Tax club',
      skills: 'Singing ',
      hobbies: 'Singing, reading and traveling ',
      favorite_course: 'Land law',
      class_crush: 'None',
      parting_words:
          '“What we call the beginning is often the end. And to make an end is to make a beginning. The end is where we start from .“'),
  Students2(
      image: 'assets/students/23.jpg',
      name: 'Adewale Feyisayo ',
      nickname: 'Shayo',
      dob: '3/13',
      state_of_origin: 'Ogun',
      mobile_number: 07080265581,
      email: 'Vivianherbiholla@gmail.com',
      linkedIn: 'Adewale Feyisayo Vivian',
      instagram: 'Vivian_biholla',
      facebook: 'Vivian Herbiholla',
      twitter: '@Hvivianne1',
      position_held: '-',
      skills: 'Baking and confectionery ',
      hobbies: 'Reading',
      favorite_course: 'Land Law ',
      class_crush: 'Nil',
      parting_words:
          '“So long as these memories lives in my heart, I shall say that life is good.”'),
  Students2(
      image: 'assets/students/24.jpg',
      name: 'Adeyemi Akinyemi ',
      nickname: 'Herrera',
      dob: '9/13',
      state_of_origin: 'Ogun',
      mobile_number: 09023952414,
      email: 'akinyemiadeyemidaniel@gmail.com',
      linkedIn: '-',
      instagram: 'y.e.m.1',
      facebook: '-',
      twitter: '-',
      position_held: 'Law Clinic : Head of Group; Freedom of Information Group',
      skills: 'Nothing really',
      hobbies: 'Video games, football, music',
      favorite_course: 'Intellectual Property Law',
      class_crush: 'None',
      parting_words: 'A wise man once said nothing at all'),
];
