// ignore_for_file: non_constant_identifier_names

class Students10 {
  String image;
  String name;
  String nickname;
  String dob;
  String state_of_origin;
  int mobile_number;
  String email;
  String linkedIn;
  String instagram;
  String facebook;
  String twitter;
  String position_held;
  String skills;
  String hobbies;
  String favorite_course;
  String class_crush;
  String parting_words;

  Students10(
      {required this.image,
      required this.name,
      required this.nickname,
      required this.dob,
      required this.state_of_origin,
      required this.mobile_number,
      required this.email,
      required this.linkedIn,
      required this.instagram,
      required this.facebook,
      required this.twitter,
      required this.position_held,
      required this.skills,
      required this.hobbies,
      required this.favorite_course,
      required this.class_crush,
      required this.parting_words});
}

List<Students10> studentList10 = [
  Students10(
      image: 'assets/students/116.jpg',
      name: 'Ogundepo Stephen oluwagbenga ',
      nickname: 'LahLah',
      dob: '12/16',
      state_of_origin: 'Oyo',
      mobile_number: 08130220998,
      email: 'Oluwagbengastephens@gmail.com',
      linkedIn: '-',
      instagram: '-',
      facebook: 'Depo Stephen oluwagbenga',
      twitter: '-',
      position_held: '2 times Fellowship President ',
      skills: 'Speaking ',
      hobbies: 'Talking to people n counseling ',
      favorite_course: 'Women and the law ',
      class_crush: '-',
      parting_words: '-'),
  Students10(
      image: 'assets/students/119.jpg',
      name: 'Ogunjimi Ayomikun Elizabeth',
      nickname: 'Mikun, A.E Ogunjimi',
      dob: '6/13',
      state_of_origin: 'Ogun',
      mobile_number: 08180726434,
      email: 'aogunjimi099@gmail.com',
      linkedIn: 'Ayomikun Ogunjimi',
      instagram: '@TalentMikun',
      facebook: 'Ogunjimi Lizzie Ayomikun',
      twitter: '@Homohlasho',
      position_held:
          'JB Summit HOM Drama, JB Summit HOD Drama, TIC Vice President, TIC Prayer Cordinator, Campus Mirror President, Campus Mirror Vice President, Campus Mirror General Secretary, NISS Ex-Officio, NISS Legal Adviser amongst others',
      skills: 'I\'ve learnt management and team playing skills.',
      hobbies: 'Learning',
      favorite_course: 'Criminal Law',
      class_crush: 'Tminor',
      parting_words:
          'I\'ve met you all in part and related with you in part, and you will forever remain a part of me. I miss Class Achievers so much.'),
  Students10(
      image: 'assets/students/120.jpg',
      name: 'Ogunjumelo Bisola',
      nickname: 'Bisola',
      dob: '4/7',
      state_of_origin: 'Ogun',
      mobile_number: 09059362905,
      email: 'Toyino362@gmail.com',
      linkedIn: '-',
      instagram: 'Jumelo_bisola',
      facebook: 'Ogunjumelo bisola ',
      twitter: 'Bee bee',
      position_held: '-',
      skills: 'Baking',
      hobbies: 'Travelling, watching movies',
      favorite_course: 'Women and the law',
      class_crush: '-',
      parting_words: 'In anything you do, love God and have money'),
  Students10(
      image: 'assets/students/121.jpg',
      name: 'Ogunlewe Oluwatosin Ayisat ',
      nickname: 'Lewe',
      dob: '11/6',
      state_of_origin: 'Lagos',
      mobile_number: 08170985215,
      email: 'Oluwatosinayisat@gmail.com',
      linkedIn: '-',
      instagram: 'Toks_glam__',
      facebook: 'Ogunlewe Tosin',
      twitter: '-',
      position_held: '-',
      skills: 'Hair Styling and Makeup ',
      hobbies: 'I love dancing, playing ludo, watching movies and making hair.',
      favorite_course: 'Women and the Law',
      class_crush: 'Ganiyu Zaynab Atinuke',
      parting_words: 'We will all be fine!'),
  Students10(
      image: 'assets/students/122.jpg',
      name: 'Ogunnowo Michael Oluwatobiloba ',
      nickname: 'Chalcedonii ',
      dob: '11/7',
      state_of_origin: 'Ogun',
      mobile_number: 09036937508,
      email: 'Ogunnowotobi@gmail.com ',
      linkedIn: '-',
      instagram: 'Chalcedonii ',
      facebook: '-',
      twitter: '@Ogunnowo',
      position_held: 'Senator',
      skills: 'I\'m good at writing. I can also work as a content creator. ',
      hobbies: 'Reading, writing and music. ',
      favorite_course: 'Intellectual Property ',
      class_crush: 'Adepeju Morenikeji',
      parting_words: '-'),
  Students10(
      image: 'assets/students/123.jpg',
      name: 'Ogunsanya Esther Ibukun',
      nickname: 'Alina',
      dob: '2/19',
      state_of_origin: 'Ogun',
      mobile_number: 09031702438,
      email: 'semaahkenie@gmail.com',
      linkedIn: '-',
      instagram: 'alina_glams',
      facebook: '-',
      twitter: '-',
      position_held: '-',
      skills: 'Learnt to be good at what I do while managing stress and time .',
      hobbies: 'Derive pleasure from doing my handiwork (make-up artist).',
      favorite_course: 'Law of Contract .',
      class_crush: '-',
      parting_words:
          'Life is a puzzle, no matter how hard you try to solve it, it keeps giving you another one to solve . Don\'t be lost in solving that puzzle. Just be you! '),
  Students10(
      image: 'assets/students/124.jpg',
      name: 'Ogunsola Rofiat',
      nickname: 'Rophycandy, kikzy spending.',
      dob: '9/1',
      state_of_origin: 'Ogun',
      mobile_number: 08129782772,
      email: 'rophycandy@gmail.com',
      linkedIn: 'Ogunsola Rofiat',
      instagram: 'rophycandy',
      facebook: '-',
      twitter: 'Kikeofcanada',
      position_held:
          '"Financial secretary ooulawss 2016/2017 Chief welfare Namlas OOU"',
      skills: 'Pastry and dessert making',
      hobbies: 'Cooking and eating.',
      favorite_course: 'Taxation',
      class_crush: 'Rofiat',
      parting_words: '-'),
  Students10(
      image: 'assets/students/126.jpg',
      name: 'Ojugbele Medinah Enitan',
      nickname: 'Marabella',
      dob: '4/18',
      state_of_origin: 'Ogun',
      mobile_number: 09082339975,
      email: 'marabella049@gmail.com',
      linkedIn: '-',
      instagram: 'marabella049',
      facebook: 'Ojugbele Medinah',
      twitter: '-',
      position_held: 'Treasurer',
      skills: 'Marketing',
      hobbies: 'Watching movies,listening to music,cooking,watching football ',
      favorite_course: 'Criminology',
      class_crush: '-',
      parting_words: '-'),
  Students10(
      image: 'assets/students/127.jpg',
      name: 'Oke Oluwagbemiga Ayomide',
      nickname: 'Jmine',
      dob: '1/4',
      state_of_origin: 'Ogun',
      mobile_number: 07062300196,
      email: 'olusolagbenga1@gmail.com',
      linkedIn: '-',
      instagram: 'Ayor_Jmine',
      facebook: 'Olusola Gbenga',
      twitter: 'Ayor_Jmine',
      position_held:
          '18/19 SUG PECO P.R.O, Deputy Coordinator PACI, HOC Yusuf Ali Chambers. E plenty abeg.',
      skills: 'Leadership skills, team player, Editing, Graphics',
      hobbies: 'Football, Songwriting, Catching Cruise',
      favorite_course: '-',
      class_crush: 'Solafunmi💕',
      parting_words:
          'Jah blessings and Favour with Good luck on everyone while facing every phase of life. '),
  Students10(
      image: 'assets/students/128.jpg',
      name: 'Okeowo kayode Joshua',
      nickname: 'Capt. Josh',
      dob: '12/21',
      state_of_origin: 'Ogun',
      mobile_number: 07064721344,
      email: 'Lordjoshua114@gmail.com',
      linkedIn: 'okeowo kayode joshua',
      instagram: 'okeowo kayode joshua',
      facebook: 'okeowo kayode joshua',
      twitter: '@lordjoshua',
      position_held:
          'Ass. Project director and Librarian2 @ inner temple, Assistant financial secretary @ legal achievers fyb committe, Zonal head usher @ RCCG, ago- iwoye.',
      skills: '-',
      hobbies: 'studying and music',
      favorite_course: 'Family law',
      class_crush: 'Peju',
      parting_words:
          'It isn\'t about how far but how well; work in accordance to God\'s purpose for your life and the best would come your way.'),
];
