// ignore_for_file: non_constant_identifier_names

class Students15 {
  String image;
  String name;
  String nickname;
  String dob;
  String state_of_origin;
  int mobile_number;
  String email;
  String linkedIn;
  String instagram;
  String facebook;
  String twitter;
  String position_held;
  String skills;
  String hobbies;
  String favorite_course;
  String class_crush;
  String parting_words;

  Students15(
      {required this.image,
      required this.name,
      required this.nickname,
      required this.dob,
      required this.state_of_origin,
      required this.mobile_number,
      required this.email,
      required this.linkedIn,
      required this.instagram,
      required this.facebook,
      required this.twitter,
      required this.position_held,
      required this.skills,
      required this.hobbies,
      required this.favorite_course,
      required this.class_crush,
      required this.parting_words});
}

List<Students15> studentList15 = [
  Students15(
      image: 'assets/students/183.jpg',
      name: 'Shenneye nofisat busayo',
      nickname: '-',
      dob: '7/11',
      state_of_origin: 'Ogun',
      mobile_number: 08138913848,
      email: 'shenneyenofisat@gmail.com',
      linkedIn: '-',
      instagram: '-',
      facebook: 'Shenneye nafeesah oluwabusayomi',
      twitter: '-',
      position_held: 'Namlas vp1, mssn naibatul ameera',
      skills: 'Selling ',
      hobbies: 'Cooking, hangout, read, and counsel',
      favorite_course: 'Contract law',
      class_crush: '-',
      parting_words: 'Live and not just breathe, the life is all about you. '),
  Students15(
      image: 'assets/students/184.jpg',
      name: 'Shobande Ouwapelumi Ayomide.',
      nickname: 'Pearl.',
      dob: '4/29',
      state_of_origin: 'Ogun',
      mobile_number: 08094502359,
      email: 'oluwapelumishobande1@gmail.com',
      linkedIn: '-',
      instagram: 'Pearl_shobabs',
      facebook: 'Pelumi Morenikeji',
      twitter: '-',
      position_held: '-',
      skills: 'Hair Styling',
      hobbies: 'Reading Novels',
      favorite_course: 'Criminology',
      class_crush: '-',
      parting_words: '-'),
  Students15(
      image: 'assets/students/185.jpg',
      name: 'Sholagbade Oluwakamisi  Michelle ',
      nickname: 'Kashme',
      dob: '8/20',
      state_of_origin: 'Ogun',
      mobile_number: 08170675001,
      email: 'Kashme555@gmail.com',
      linkedIn: '-',
      instagram: '@_kashmee',
      facebook: 'Sholagbade oluwakamisi ',
      twitter: '@sholagbadeoluw3',
      position_held: 'Fin sec, IP club',
      skills: '-',
      hobbies: 'Cooking, surfing the web',
      favorite_course: 'Family law',
      class_crush: '-',
      parting_words: 'And now the ACTUAL hard work starts.'),
  Students15(
      image: 'assets/students/186.jpg',
      name: 'Shomoye Khafilat Motunrayo',
      nickname: 'Khafysho',
      dob: '4/10',
      state_of_origin: 'Ogun',
      mobile_number: 08183201091,
      email: 'Khafysho@gmail.com',
      linkedIn: 'Shomoye khafilat',
      instagram: 'Shomoye khafilat',
      facebook: 'Shomoye khafilat',
      twitter: 'Shomoye khafilat',
      position_held: 'Assistant general secretary to the tax club oou',
      skills: 'Baking and interior and exterior decoration',
      hobbies: 'Reading novels,watching movies and dancing',
      favorite_course: 'Taxation',
      class_crush: '-',
      parting_words:
          'May we meet later on in the high places and I wish us all the best of best. See you all.'),
  Students15(
      image: 'assets/students/187.jpg',
      name: 'Sobowale Olamide Oluwafisayomi ',
      nickname: 'Orlie ',
      dob: '1/17',
      state_of_origin: 'Ogun',
      mobile_number: 08180698948,
      email: 'Sobowaleolamideoluwafisayomi@gmail.com ',
      linkedIn: 'daia',
      instagram: 'Orlieshoby',
      facebook: '-',
      twitter: '-',
      position_held:
          '"General Secretary of the Winners Campus Fellowship Coordinator of the Vision Builders Drama Family "',
      skills: 'Sewing',
      hobbies: 'Cooking',
      favorite_course: 'Land law/Conveyancing ',
      class_crush: '-',
      parting_words:
          'Live your life with integrity and not give in to peer pressure or try to be what you\'re not '),
  Students15(
      image: 'assets/students/189.jpg',
      name: 'Solaru Adeola ',
      nickname: '-',
      dob: '8/24',
      state_of_origin: 'Ogun',
      mobile_number: 08113145315,
      email: 'Solaruadeola@gmail.com ',
      linkedIn: '-',
      instagram: 'Folawee.x',
      facebook: 'Solaru Adeola ',
      twitter: '-',
      position_held: '-',
      skills: 'Make up',
      hobbies: 'Reading novels and traveling ',
      favorite_course: 'Family law',
      class_crush: 'Gbemi and peter',
      parting_words: 'Start where you are. Use what you have. Do what you can'),
  Students15(
      image: 'assets/students/190.jpg',
      name: 'Soluade Oluwasegun Abiodun',
      nickname: 'Segzy',
      dob: '6/26',
      state_of_origin: 'Ogun',
      mobile_number: 07069329780,
      email: 'sego4uu@gmail.com',
      linkedIn: 'Oluwasegun Soluade',
      instagram: 'Prince Oluwasegun Soluade',
      facebook: 'Prince Soluade Oluwasegun Abiodun',
      twitter: '@sego4uu',
      position_held:
          'HOC, ADR Law Clinic;. HOC, Funke Adekoya Chambers;. General Secretary LSS Electoral Commission',
      skills: 'Project, Brief, Article, Thesis and Essay Writing',
      hobbies: 'Researching',
      favorite_course: 'Land Law',
      class_crush: 'God',
      parting_words:
          'Importance of man is not noticable when he is around but when is far away... Cherishing others is dignifying'),
  Students15(
      image: 'assets/students/191.jpg',
      name: 'Sule Salawa Abike',
      nickname: 'Solace',
      dob: '6/9',
      state_of_origin: 'Ogun',
      mobile_number: 08104746175,
      email: 'sulaimansalwa96@gmail.com',
      linkedIn: 'Sule Salawa',
      instagram: 'Sulaiman Salawa',
      facebook: 'Sulaiman Salawa',
      twitter: 'Sulaiman Salawa',
      position_held: '-',
      skills:
          'Over time, I\'ve learnt to be independent as that tend to earn one more respect',
      hobbies: 'Reading and Cooking',
      favorite_course: 'Family Law',
      class_crush: '-',
      parting_words:
          'We should at every point in time, try to reach out to one another'),
  Students15(
      image: 'assets/students/192.jpg',
      name: 'Taiwo Oluwasanjo Ayomide',
      nickname: 'Sanjo',
      dob: '2/7',
      state_of_origin: 'Ogun',
      mobile_number: 08053280253,
      email: 'sanjotaiwo01@gmail.com',
      linkedIn: 'daia',
      instagram: '_ayo_midee',
      facebook: 'Taiwo Oluwasanjo',
      twitter: 'Ayothefather',
      position_held: '-',
      skills: 'Football, table tennis',
      hobbies: 'Sleeping and Eating',
      favorite_course: 'Criminology',
      class_crush: 'Charles',
      parting_words: 'One step at a time'),
  Students15(
      image: 'assets/students/193.jpg',
      name: 'Talabi Elizabeth Oluwakemi ',
      nickname: 'Lizzy',
      dob: '12/21',
      state_of_origin: 'Ogun',
      mobile_number: 08166071452,
      email: 'Kemibiodun97@yahoo.com',
      linkedIn: '-',
      instagram: 'Theolukemitalabi',
      facebook: 'Elizabeth Talabi',
      twitter: 'The_olukemitalabi',
      position_held: '-',
      skills: 'Hairdressing and beadmaking ',
      hobbies: 'Watching movies and travelling',
      favorite_course: 'Commercial law',
      class_crush: 'Hahahaha',
      parting_words: 'Do all things decently and in order.'),
];
