// ignore_for_file: non_constant_identifier_names

class Students {
  String image;
  String name;
  String nickname;
  String dob;
  String state_of_origin;
  int mobile_number;
  String email;
  String linkedIn;
  String instagram;
  String facebook;
  String twitter;
  String position_held;
  String skills;
  String hobbies;
  String favorite_course;
  String class_crush;
  String parting_words;

  Students(
      {required this.image,
      required this.name,
      required this.nickname,
      required this.dob,
      required this.state_of_origin,
      required this.mobile_number,
      required this.email,
      required this.linkedIn,
      required this.instagram,
      required this.facebook,
      required this.twitter,
      required this.position_held,
      required this.skills,
      required this.hobbies,
      required this.favorite_course,
      required this.class_crush,
      required this.parting_words});
}

List<Students> studentList = [
  Students(
      image: 'assets/students/2.jpg',
      name: 'Adepeju Eniola Morenikeji',
      nickname: 'Peju',
      dob: '3/17',
      state_of_origin: 'Ogun',
      mobile_number: 08165765168,
      email: 'ehnniyola17@gmail.com',
      linkedIn: 'Adepeju Morenikeji ',
      instagram: 'Ehnniyola ',
      facebook: 'Morenikeji Adepeju ',
      twitter: 'Ehnniyola ',
      position_held:
          ' FSF Financial Secretary/Head Usher’18\nFSF Financial Secretary/Head Usher/Sis Cord’19\nFSF Financial Secretary’20\nFace of law’20\nLAWSAN Campus Director’21\nTecno ambassador’21\nLBI Zonal ambassador’21 ',
      skills: 'Wigging, writing ',
      hobbies: 'Sleeping, talking and watching movies ',
      favorite_course: 'Criminology ',
      class_crush: 'All the cute guys in our class',
      parting_words:
          'My prayer is that when we meet outside OOU we do not have to dodge from one another '),
  Students(
      image: 'assets/students/3.jpg',
      name: 'Abass Oluwatosin Zainab ',
      nickname: 'Zinnia',
      dob: '3/19',
      state_of_origin: 'Ogun',
      mobile_number: 08069434686,
      email: 'tosinzenn@gmail.com',
      linkedIn: '-',
      instagram: 'Zinnia_11',
      facebook: 'Abass Oluwatosin',
      twitter: 'Ziniiaa',
      position_held:
          'Lspc honourable 400 level\nFyb yearbook committee chairman ',
      skills: 'Listening',
      hobbies:
          'Watching movies/tv series, reading novels, overthinking, sleeping, eating, fangirling. ',
      favorite_course: 'Family law and women and the law ',
      class_crush: 'All the beautiful girls. ',
      parting_words:
          'If you\'re brave enough to say goodbye, life will reward you with a new hello - Paul Coelho'),
  Students(
      image: 'assets/students/4.jpg',
      name: 'Abdulrasheed Agboola ',
      nickname: 'Rashford ',
      dob: '2/27',
      state_of_origin: 'Oyo',
      mobile_number: 07037457183,
      email: 'Agboolarasheed21@gmail.com',
      linkedIn: 'Abdulrasheed Agboola',
      instagram: 'Bobo_del ',
      facebook: 'Abdulrasheed Agboola ',
      twitter: 'Bobo_dell',
      position_held:
          'Sports Director, OOULSS, 18/19. HOG, Law Reform/Advocacy, OOU Law Clinic, 20/21.',
      skills: '-',
      hobbies: 'Nothing',
      favorite_course: 'Petroleum and energy Law',
      class_crush: 'Nill',
      parting_words: 'We live to Die💀'),
  /*Students(
      image: 'assets/students/5.jpg',
      name: 'Abdussalam Abdulfatai Tantolorun ',
      nickname: 'Zamani',
      dob: '7/18',
      state_of_origin: 'Ogun ',
      mobile_number: 09064824268,
      email: 'Zamanifunds@gmail.com',
      linkedIn: '-',
      instagram: 'Zamani__lyon',
      facebook: '-',
      twitter: '@yonzamani',
      position_held: '-',
      skills: 'Football',
      hobbies: 'Business/ partying ',
      favorite_course: 'Women and the law',
      class_crush: 'None',
      parting_words:
          'The time spent with my colleagues has been amazing and the memories shared will forever be engraved in my heart I hope we all achieve our heart desires in the nearest future '),*/
  Students(
      image: 'assets/students/6.jpg',
      name: 'Abdussalam Aminat Oluwatosin ',
      nickname: 'Meenah peace',
      dob: '11/28',
      state_of_origin: 'Ogun',
      mobile_number: 08090560777,
      email: 'abdussalamomotolani@gmail.com',
      linkedIn: 'Abdussalam Aminat Oluwatosin ',
      instagram: 'Meenah_peace',
      facebook: 'Abdussalam Aminat Omotolani ',
      twitter: 'Meenah_peace',
      position_held: 'Namlas Asst. chief welfare ',
      skills: 'Time management and Legal Research ',
      hobbies: 'Sleeping, eating, listening to music, dancing.',
      favorite_course: 'Law of contract ',
      class_crush: 'Nil',
      parting_words: 'Lines shall fall in pleasant places for everyone of us.'),
  Students(
      image: 'assets/students/7.jpg',
      name: 'Abdussalam Zaynab Omobolanle',
      nickname: 'Zainny',
      dob: '6/13',
      state_of_origin: 'Ogun',
      mobile_number: 08087404852,
      email: 'abdussalamzaynab@gmail.com',
      linkedIn: 'Zaynab Abdussalam',
      instagram: 'Zainny_Soaps',
      facebook: '-',
      twitter: '-',
      position_held:
          'Head of client Interview and Public Debate_Olabisi Onabanjo University Law Clinic Assistant Coordinator General_National Association of Muslim Law Students Librarian_Legal Magnate and Company ',
      skills: 'Research and Essay writing',
      hobbies: 'Watching movies',
      favorite_course: 'Evidence',
      class_crush: 'None',
      parting_words: 'Be determined in whatever you do.'),
  Students(
      image: 'assets/students/8.jpg',
      name: 'Abolaji Favour',
      nickname: 'Flavy ',
      dob: '5/28',
      state_of_origin: 'Ogun',
      mobile_number: 08140063171,
      email: 'Favourabolaji28@gmail.com',
      linkedIn: '-',
      instagram: 'Abolaji_favour',
      facebook: '-',
      twitter: 'Boss babe xxl',
      position_held: '-',
      skills: '-',
      hobbies: 'Reading novels, traveling ',
      favorite_course: 'Women and the law',
      class_crush: '-',
      parting_words: 'We made it!'),
  Students(
      image: 'assets/students/9.jpg',
      name: 'Adebanjo olusola Susan',
      nickname: '-',
      dob: '12/16',
      state_of_origin: 'Ogun',
      mobile_number: 07030313518,
      email: 'adebanjodamilola5@gmail.com',
      linkedIn: '-',
      instagram: '_symply_susan',
      facebook: '-',
      twitter: '-',
      position_held: '-',
      skills: 'Make up,tie and dye , hair styling,',
      hobbies:
          'Reading, listening to music, taking care of everyone one I love',
      favorite_course: 'Criminal law',
      class_crush: 'D',
      parting_words:
          'I am a star in the universe,from afar and insignificant  dot of light in the universe,up close a ball of fire and rage torn from every crevice of my being.Some days I wake up feeling  useless ,other days I wake up'),
  Students(
      image: 'assets/students/10.jpg',
      name: 'Adebawo Busola Elizabeth',
      nickname: 'Bubbery',
      dob: '4/24',
      state_of_origin: 'Ogun',
      mobile_number: 08147207473,
      email: 'adebawobusola@gmail.com',
      linkedIn: 'Busola Adebawo',
      instagram: 'Holuwabusolami',
      facebook: 'Adebawo Busola',
      twitter: 'Busola Adebawo',
      position_held:
          'Assistant Head of Moot and Brief Writing Department (OOU LAW CLINIC); Head of Moot and Brief Writing Department (OOU LAW CLINIC); Students Judge (500 level representative) and Academic Secretary (CIAOOCF 2018- 2020).',
      skills: 'Good customer relations; Legal research and writing.',
      hobbies: 'Singing, touring, writing and reading',
      favorite_course: 'Women and the Law and Intellectual Property',
      class_crush: 'Oyeneye Jedidiah and Stephen Samson',
      parting_words:
          'I came to Olabisi Onabanjo University (OOU) alone but I am moving ahead of the bridge with many bright learned colleagues. I pray we all find our purposes in the real world. Yeah, I will miss all my friends... I LOVE YOU ALL.❤'),
  Students(
      image: 'assets/students/11.jpg',
      name: 'Adebayo Ifeoluwa ',
      nickname: 'TheIfeoluwa',
      dob: '4/7',
      state_of_origin: 'Ogun',
      mobile_number: 09031799239,
      email: 'iolufunke04@gmail.com',
      linkedIn: 'Adebayo Ifeoluwa ',
      instagram: 'Theifeoluwa_',
      facebook: 'Adebayo Ifeoluwa ',
      twitter: 'Theifeoluwa ',
      position_held: 'Jb Summit Music Director',
      skills: 'Fashion Designing. ',
      hobbies: 'Cooking and doing music. ',
      favorite_course: 'Family Law and Law of Succession',
      class_crush: '-',
      parting_words: 'Breathe, you’re never alone.'),
  Students(
      image: 'assets/students/12.jpg',
      name: 'Adedeji Anjolaoluwa Feyikemi',
      nickname: 'Anjie',
      dob: '5/26',
      state_of_origin: 'Osun',
      mobile_number: 08178927473,
      email: 'Jolaadedeji@gmail.com',
      linkedIn: '-',
      instagram: 'Anjola.__',
      facebook: 'Adedeji Anjola',
      twitter: '-',
      position_held: 'Bible Study Coordinator',
      skills:
          'Learnt how to make shawarma during the lockdown period😌.I’m good at cooking too(definitely)',
      hobbies: 'Studying the Word,sleeping,and eating junks!',
      favorite_course:
          'Yeah I definitely like land law and family law.They’re relatable!',
      class_crush: 'Abdul oluwaseun',
      parting_words: 'Comparison is a joy killer! Do your own thing❤️'),
  Students(
      image: 'assets/students/13.jpg',
      name: 'Adekola Bolanle Mary ',
      nickname: 'Baams (Rie b)',
      dob: '5/13',
      state_of_origin: 'Ogun',
      mobile_number: 09093105590,
      email: 'adekoladebola7',
      linkedIn: 'Adekola Bolanle',
      instagram: '___baams ',
      facebook: 'Adekola Omobolanle',
      twitter: '-',
      position_held: '-',
      skills: 'Mediation ',
      hobbies:
          'Communicating, exercising, singing and making not perfect moves. ',
      favorite_course: 'Law of contract ',
      class_crush: 'Any fine boy',
      parting_words: 'Dear beautiful people, be kind. '),
  Students(
      image: 'assets/students/14.jpg',
      name: 'Adekoya Babatunde',
      nickname: 'EDNUT',
      dob: '8/13',
      state_of_origin: 'Ogun',
      mobile_number: 08147908218,
      email: 'tundednut60@gmail.com',
      linkedIn: 'Tunde Ednut',
      instagram: 'Ednut_the_photographer',
      facebook: 'EDNUT ADEKOYA',
      twitter: '_ednut',
      position_held: 'HOD Media and publicity (2018- 2020)',
      skills: 'Photography/social media influencer',
      hobbies: 'Playing table tennis',
      favorite_course: 'Nigeria Legal system',
      class_crush: 'No one',
      parting_words: '-'),
  Students(
      image: 'assets/students/15.jpg',
      name: 'Adelaja Olamide Oluwatosin ',
      nickname: 'Lam Hephzibah ',
      dob: '6/4',
      state_of_origin: 'Ogun',
      mobile_number: 08111182017,
      email: 'Adelajaolamide7@gmail.com',
      linkedIn: '-',
      instagram: 'Hephmillie_xx',
      facebook: 'Heph Zibah ',
      twitter: '@Hephzibah_lam',
      position_held: 'Best of d Best ',
      skills: 'I love creating Artworks 🖼, drawing ✍️ painting',
      hobbies: 'Football, Music , Food, 4:20, Money 💰 ',
      favorite_course: 'Criminology ',
      class_crush: 'Rather not say',
      parting_words: 'Never Lose Hope coz NHL🧢💯'),
  Students(
      image: 'assets/students/16.jpg',
      name: 'Adeleke Peter adewale',
      nickname: 'Wale_deleke',
      dob: '11/5',
      state_of_origin: 'Oyo',
      mobile_number: 08109858985,
      email: 'Adelekepeter13@gmail.com',
      linkedIn: 'Adele Peter',
      instagram: 'Wale_Deleke',
      facebook: 'Peter Adeleke',
      twitter: 'Wale_deleke',
      position_held:
          'General secretary for Niyi Akintola chamber Assistant general secretary for intellectual property club,Oou. ',
      skills: 'Researching, ability to work under pressure, negotiating skills',
      hobbies: 'Watching football,listening to music ',
      favorite_course: 'Family law',
      class_crush: '😂😂😂 I no answer boss ',
      parting_words:
          'Well change is the constant thing in life but change itself isn’t constant.'),
  Students(
      image: 'assets/students/17.jpg',
      name: 'Ademuyiwa Adekolapo Hazeez',
      nickname: 'Kolapo',
      dob: '4/3',
      state_of_origin: 'Ogun',
      mobile_number: 08151309084,
      email: 'ademuyiwaadekolapo@gmail.com',
      linkedIn: '-',
      instagram: 'Ade_kholapo',
      facebook: '-',
      twitter: 'Ade_kholapo',
      position_held: '-',
      skills: 'Play football ',
      hobbies: 'Play football ',
      favorite_course: 'Family law ',
      class_crush: 'Bisola',
      parting_words: '-'),
  Students(
      image: 'assets/students/18.jpg',
      name: 'Adeniji Anuoluwapo Elizabeth ',
      nickname: 'Mercyluxury',
      dob: '10/16',
      state_of_origin: 'Ogun',
      mobile_number: 07065478578,
      email: 'mercyelizabethblaze@gmail.com',
      linkedIn: '@Mercyelizabeth',
      instagram: '_mercyelizabeth ',
      facebook: 'Adeniji Elizabeth ',
      twitter: 'Mercyelizabeth ',
      position_held: '-',
      skills: 'Business ',
      hobbies: 'Swimming, Going out, Shopping and Discovering New Locations.',
      favorite_course:
          'Women and the law, because it taught me so much about womanhood and it’s rights',
      class_crush: 'Peterclaver in 100level ',
      parting_words:
          'It was a great pleasure to be in the same class as you brilliant folks and I love y’all '),
  /*Students(
      image: 'assets/students/19.jpg',
      name: 'Adenuga Paul',
      nickname: '-',
      dob: '10/30',
      state_of_origin: 'Ogun',
      mobile_number: 07064306722,
      email: 'hadenugapaul@gmail.com',
      linkedIn: '-',
      instagram: 'Paul_adenuga2',
      facebook: '-',
      twitter: '-',
      position_held: '-',
      skills: 'Tech',
      hobbies: 'Tech, gaming and having money ',
      favorite_course: 'Women and the law',
      class_crush: 'Oreoluwa Kendore',
      parting_words: '-'),*/
  Students(
      image: 'assets/students/20.jpg',
      name: 'Adeola Elizabeth Ayanbanjo ',
      nickname: 'Adey ',
      dob: '2/23',
      state_of_origin: 'Ogun',
      mobile_number: 08109821598,
      email: 'Ayanbanjoelizabeth62@gmail.com',
      linkedIn: 'Adeola Ayanbanjo',
      instagram: 'hardey_horlahr1',
      facebook: 'Ayanbanjo Adeola Elizabeth ',
      twitter: '-',
      position_held:
          'OOUSUG Judicial council Registrar, Clasfon welfare director, Veecee success stories Editor, Veecee success stories Analyst/Vice President ',
      skills: '-',
      hobbies: 'Watching movies, listening to music and traveling ',
      favorite_course:
          'Women and the law. The course is just so relatable and doesn’t require extra.',
      class_crush: 'None',
      parting_words:
          'It’s sad, but sometimes moving on with the rest of your life, starts with goodbye. – Carrie Underwood'),
  Students(
      image: 'assets/students/21.jpg',
      name: 'Adeosun Favour Oluwakamimayo',
      nickname: 'Fefe of law',
      dob: '6/16',
      state_of_origin: 'Ogun',
      mobile_number: 09035518381,
      email: 'foluwakamimayo10@gmail.com',
      linkedIn: 'Favour Adeosun',
      instagram: 'fe_fe_a',
      facebook: 'Favour Adeosun',
      twitter: 'Fefe',
      position_held:
          'President Veecee Success Stories\nGen.Sec Tax club\nPresident Tax club ',
      skills: 'Writing ',
      hobbies: 'Writing, cooking and meeting people',
      favorite_course: 'Tax law',
      class_crush: 'None',
      parting_words:
          'Whatever your mind can conceive it can achieve, never limit yourself for any reason. '),
  Students(
      image: 'assets/students/22.jpg',
      name: 'Adeoye Praise Adejoke',
      nickname: 'Joke',
      dob: '7/3',
      state_of_origin: 'Lagos',
      mobile_number: 08024491459,
      email: 'Praiseadejoke@gmail.com',
      linkedIn: '-',
      instagram: 'Titt_up',
      facebook: 'Praise Adeoye',
      twitter: 'Adeoye praise 2',
      position_held: 'Welfare director of Tax club',
      skills: 'Singing ',
      hobbies: 'Singing, reading and traveling ',
      favorite_course: 'Land law',
      class_crush: 'None',
      parting_words:
          '“What we call the beginning is often the end. And to make an end is to make a beginning. The end is where we start from .“'),
  /* Students(
      image: 'assets/students/23.jpg',
      name: 'Adewale Feyisayo ',
      nickname: 'Shayo',
      dob: '3/13',
      state_of_origin: 'Ogun',
      mobile_number: 07080265581,
      email: 'Vivianherbiholla@gmail.com',
      linkedIn: 'Adewale Feyisayo Vivian',
      instagram: 'Vivian_biholla',
      facebook: 'Vivian Herbiholla',
      twitter: '@Hvivianne1',
      position_held: '-',
      skills: 'Baking and confectionery ',
      hobbies: 'Reading',
      favorite_course: 'Land Law ',
      class_crush: 'Nil',
      parting_words:
          '“So long as these memories lives in my heart, I shall say that life is good.”'),*/
  Students(
      image: 'assets/students/24.jpg',
      name: 'Adeyemi Akinyemi ',
      nickname: 'Herrera',
      dob: '9/13',
      state_of_origin: 'Ogun',
      mobile_number: 09023952414,
      email: 'akinyemiadeyemidaniel@gmail.com',
      linkedIn: '-',
      instagram: 'y.e.m.1',
      facebook: '-',
      twitter: '-',
      position_held: 'Law Clinic : Head of Group; Freedom of Information Group',
      skills: 'Nothing really',
      hobbies: 'Video games, football, music',
      favorite_course: 'Intellectual Property Law',
      class_crush: 'None',
      parting_words: 'A wise man once said nothing at all'),
];
