// ignore_for_file: non_constant_identifier_names

class Students14 {
  String image;
  String name;
  String nickname;
  String dob;
  String state_of_origin;
  int mobile_number;
  String email;
  String linkedIn;
  String instagram;
  String facebook;
  String twitter;
  String position_held;
  String skills;
  String hobbies;
  String favorite_course;
  String class_crush;
  String parting_words;

  Students14(
      {required this.image,
      required this.name,
      required this.nickname,
      required this.dob,
      required this.state_of_origin,
      required this.mobile_number,
      required this.email,
      required this.linkedIn,
      required this.instagram,
      required this.facebook,
      required this.twitter,
      required this.position_held,
      required this.skills,
      required this.hobbies,
      required this.favorite_course,
      required this.class_crush,
      required this.parting_words});
}

List<Students14> studentList14 = [
  Students14(
      image: 'assets/students/172.jpg',
      name: 'Qudus Akinyemi Ayomide',
      nickname: '-',
      dob: '7/8',
      state_of_origin: 'Ogun',
      mobile_number: 07051095641,
      email: 'qudusakinyemi8@gmail.com',
      linkedIn: '-',
      instagram: 'instagram@yvessaintladen',
      facebook: '-',
      twitter: 'twitter@sex',
      position_held: '-',
      skills: '-',
      hobbies: 'Vibing',
      favorite_course: 'Petroleum and Energy law',
      class_crush: '-',
      parting_words: '-'),
  Students14(
      image: 'assets/students/173.jpg',
      name: 'Rotimi Muyiwa Jacob',
      nickname: 'RTECH',
      dob: '1/6',
      state_of_origin: 'Ondo',
      mobile_number: 07061032844,
      email: 'young09033@gmail.com',
      linkedIn: '-',
      instagram: 'rtech_business_services',
      facebook: 'ROTIMI YOUNGSTAR OLAMUYIWA',
      twitter: 'Longtrick1997',
      position_held: '-',
      skills: '-',
      hobbies:
          'Playing games, watching football, singing and listening to songs.',
      favorite_course: 'Law of Torts',
      class_crush: '*****',
      parting_words: 'We all meet at the top💯'),
  Students14(
      image: 'assets/students/174.jpg',
      name: 'Salami Abolanle Olaide',
      nickname: 'Skinethics',
      dob: '8/8',
      state_of_origin: 'Ogun',
      mobile_number: 07031213066,
      email: 'Salamibolanle62@gmail.com',
      linkedIn: '-',
      instagram: 'Dunni_nii',
      facebook: 'Salami Bolanle',
      twitter: '-',
      position_held: 'Treasure',
      skills: 'Anything skincare',
      hobbies: 'Making herbs ',
      favorite_course: 'Women and the Law',
      class_crush: 'Ajide Ibukunoluwa',
      parting_words: 'Take good care of yourself!'),
  Students14(
      image: 'assets/students/176.jpg',
      name: 'Salawu Farook Adeniyi',
      nickname: '-',
      dob: '2/9',
      state_of_origin: '2/9',
      mobile_number: 08035566302,
      email: 'farooksalawu@gmail.com ',
      linkedIn: 'Farook Salawu',
      instagram: 'fa_salawu',
      facebook: 'Farook Salawu',
      twitter: 'Farook_Salawu',
      position_held: 'Vice Preseident 2, Namlas. ',
      skills: '-',
      hobbies: '-',
      favorite_course: '-',
      class_crush: '-',
      parting_words: '-'),
  Students14(
      image: 'assets/students/177.jpg',
      name: 'Salomi Deborah',
      nickname: 'Deborah Levite ',
      dob: '10/15',
      state_of_origin: 'Ogun',
      mobile_number: 07056034623,
      email: 'salomitolulope@gmail.com',
      linkedIn: 'Salomi Deborah',
      instagram: 'Salomi Deborah',
      facebook: 'Salomi Deborah',
      twitter: 'Salomi Deborah',
      position_held: '-',
      skills: 'Writing novels and publishing books for people ,Acting .',
      hobbies: 'Writing,Reading books and Acting .',
      favorite_course: '-',
      class_crush: 'Holy Spirit ',
      parting_words: 'jnjJesus loves you .i'),
  Students14(
      image: 'assets/students/178.jpg',
      name: 'Salu Azeezat Motunrayo',
      nickname: 'ZEERAYO/ A.Z.',
      dob: '8/16',
      state_of_origin: 'Ogun',
      mobile_number: 08137363599,
      email: 'saluazeezat@gmail.com',
      linkedIn: '-',
      instagram: '_rayo_xx / ZeeRayo_Apparels08',
      facebook: 'AZEEZAT SALU',
      twitter: '-',
      position_held: '-',
      skills: 'BUSINESS STRATEGIES ',
      hobbies: 'DOING LEGAL BUSINESSES ',
      favorite_course: 'LAW OF CONTRACT',
      class_crush: '-',
      parting_words:
          'No distance of place or lapse of time can lessen the friendship of those who are thoroughly persuaded of each other’s worth.Farewell Family ! '),
  Students14(
      image: 'assets/students/179.jpg',
      name: 'Sam Ayomikun',
      nickname: 'P. Sam',
      dob: '4/22',
      state_of_origin: 'Ogun',
      mobile_number: 07049160691,
      email: 'samayomikun98@gmail.coms',
      linkedIn: '-',
      instagram: 'Samayomikun01',
      facebook: 'Sam Ayomikun',
      twitter: 'Samayomikun',
      position_held:
          'President of CACSA and Gen. Sec of the Joint Believers Summit',
      skills: '-',
      hobbies: 'Worshipping and Dancing',
      favorite_course: 'Family Law',
      class_crush: '-',
      parting_words:
          'It has been a nice time being part of the class and my parting words is that we all meet at the top in great places making our generation proud of us.'),
  Students14(
      image: 'assets/students/180.jpg',
      name: 'Samson Stephen',
      nickname: 'S.O.S, sammyGreat, Sam',
      dob: '6/27',
      state_of_origin: 'Enugu',
      mobile_number: 09031171925,
      email: 'gsamsonstephen@gmail.com',
      linkedIn: 'Samson Stephen',
      instagram: '@iamsamson_stephen',
      facebook: 'sammy.o.stpehen',
      twitter: 'Samsonstephen96',
      position_held:
          '"2017/2018 - Assistant Media Director/PRO @ RCFOOU 2018/2019 - Media Director/PRO @ RCFOOU, 2018 - 2021 - Member Project Committee @ RCFOOU 2018/2019 - OOULAWSS Electoral Committee (OOULAWSSECO PRO), 2021/2022 - OOULAWSS ECO CONTRACTOR FOR FIRST FACULTY OF LAW ONLINE ELECTION, Coordinator - Ogun State Google Local Guides, 2021/2022 - Head Clinician @ OOULAW CLINIC, 2020/2021 - Governor General & Head of OOU LAW STUDENTS\' GOVERNORS COUNCIL, 2016/17 - 2021/22 - Class Governor, The Legal Achievers Class,"',
      skills:
          'Entrepreneurship, Public Speaking, Leadership, Managerial and Organisational skills, ',
      hobbies:
          'Listening to Music, Seeing Nature, Traveling/Adventure, Mapping with Google Maps, Learning new things.',
      favorite_course: 'Human Rights',
      class_crush: 'Adeola',
      parting_words:
          'Its been a great time well spent learning the act of selfless service and I am most grateful for the opportunity to learn, to build relationships and to grow, I will forever remain grateful. - Samson Stephen'),
  Students14(
      image: 'assets/students/181.jpg',
      name: 'Sanwo Francisca Olubusola',
      nickname: '-',
      dob: '3/9',
      state_of_origin: 'Ogun',
      mobile_number: 08070640533,
      email: 'franciscabusola@gmail.com',
      linkedIn: '-',
      instagram: 'fancy_mhee',
      facebook: 'Francisca Sanwo',
      twitter: '@Francisca.O.S',
      position_held: 'Member, Election Petition Committee(2019)',
      skills: 'Make-up Artist',
      hobbies: 'Singing',
      favorite_course: 'Conveyancing Law',
      class_crush: '-',
      parting_words: '-'),
  Students14(
      image: 'assets/students/182.jpg',
      name: 'Seunfunmi Adekoya',
      nickname: '-',
      dob: '6/9',
      state_of_origin: 'Lagos',
      mobile_number: 07068101470,
      email: 'theseunfunmi@gmail.com',
      linkedIn: 'Seunfunmi Adekoya',
      instagram: 'theonlyseunfunmi',
      facebook: '-',
      twitter: 'theonlyseunfunmi',
      position_held: 'Class Representative, Diploma',
      skills: 'Project Management, Media Communications. ',
      hobbies: 'Watching movies. ',
      favorite_course: 'Environmental Law',
      class_crush: '-',
      parting_words: 'love & light.❤️'),
];
