// ignore_for_file: non_constant_identifier_names

class Students9 {
  String image;
  String name;
  String nickname;
  String dob;
  String state_of_origin;
  int mobile_number;
  String email;
  String linkedIn;
  String instagram;
  String facebook;
  String twitter;
  String position_held;
  String skills;
  String hobbies;
  String favorite_course;
  String class_crush;
  String parting_words;

  Students9(
      {required this.image,
      required this.name,
      required this.nickname,
      required this.dob,
      required this.state_of_origin,
      required this.mobile_number,
      required this.email,
      required this.linkedIn,
      required this.instagram,
      required this.facebook,
      required this.twitter,
      required this.position_held,
      required this.skills,
      required this.hobbies,
      required this.favorite_course,
      required this.class_crush,
      required this.parting_words});
}

List<Students9> studentList9 = [
  Students9(
      image: 'assets/students/104.jpg',
      name: 'Nwaigbo Oluchi Joan',
      nickname: '-',
      dob: '11/20',
      state_of_origin: 'Imo',
      mobile_number: 09012059825,
      email: 'anniedre845@gmail.com',
      linkedIn: '-',
      instagram: '-',
      facebook: 'Oluchy Lulu Nwaigbo',
      twitter: '-',
      position_held: '-',
      skills: '-',
      hobbies: 'I love singing and writing songs',
      favorite_course: 'Women and the Law, Criminology ',
      class_crush: '-',
      parting_words: 'Nothing is impossible..Just take a leap of faith!'),
  Students9(
      image: 'assets/students/106.jpg',
      name: 'Odubela Oluwaferanmi Adebola',
      nickname: 'Ferry',
      dob: '1/21',
      state_of_origin: 'Ogun',
      mobile_number: 08160266321,
      email: 'Oluwaferanmiodubela@gmail.com ',
      linkedIn: '-',
      instagram: 'odubela_',
      facebook: 'Luminajnr Odubela',
      twitter: 'Luminajnr ',
      position_held: '-',
      skills: 'Drawing ',
      hobbies: 'Watch football ',
      favorite_course: 'Family Law',
      class_crush: '-',
      parting_words:
          'Every minute spent with you guys for the past few years have been amazing and great. Thanks for all the good gesture. '),
  Students9(
      image: 'assets/students/107.jpg',
      name: 'Odudare ifeoluwa gift',
      nickname: 'ife',
      dob: '4/5',
      state_of_origin: 'Osun ',
      mobile_number: 08168555626,
      email: 'Ifeoluwagift0@gmail.com',
      linkedIn: 'Odudare ifeoluwa gift',
      instagram: 'Iffy_gurl',
      facebook: 'ifeoluwagift',
      twitter: '-',
      position_held:
          '"Oou sug Welfare committee vice chairman 19/20 OOU SUG Welfare director 20/21 TECNO CAMPUS REP 20/21 NAOSS(Osun) president 20/21"',
      skills: '"Fashion designing Mini importation"',
      hobbies: '"watching movies Reading books"',
      favorite_course: 'Criminology',
      class_crush: '-',
      parting_words: 'I hope to see us all in high places'),
  Students9(
      image: 'assets/students/108.jpg',
      name: 'Odufuwa omoyosola habebat ',
      nickname: '-',
      dob: '7/26',
      state_of_origin: 'Ogun',
      mobile_number: 08182336154,
      email: 'Yosolaodufuwa@gmail.com ',
      linkedIn: '-',
      instagram: 'Yossy_odufuwa ',
      facebook: 'Omoyosola Odufuwa ',
      twitter: 'Cereal addict ',
      position_held: 'An Honorable of the LSPC',
      skills: 'Sewing,makeup and press on nails ',
      hobbies: 'Reading, traveling to new places, writing ',
      favorite_course: 'I don\'t have one, I am wide spread ',
      class_crush: '-',
      parting_words:
          'Never forget life is a journey, you can always make a road stop, change directions but ensure you keep moving. '),
  Students9(
      image: 'assets/students/109.jpg',
      name: 'Odugbesan Boluwatife Gbemi',
      nickname: '5th OG',
      dob: '11/1',
      state_of_origin: 'Ogun',
      mobile_number: 08141218771,
      email: 'Odusgbemmy@gmail.com',
      linkedIn: '-',
      instagram: '5thgee',
      facebook: 'Odugbesan Aduragbemi',
      twitter: '-',
      position_held: 'The OG OF IG ',
      skills: '-',
      hobbies: 'Traveling ',
      favorite_course: 'Family Law',
      class_crush: 'All the Ladies',
      parting_words: 'A,B,C,D,E,F & HEARTBREAKS !!!'),
  Students9(
      image: 'assets/students/110.jpg',
      name: 'Odumosu Olaoluwa Olakusehin ',
      nickname: 'OLABATA ',
      dob: '7/24',
      state_of_origin: 'Ogun',
      mobile_number: 08184852970,
      email: 'odumosuolaoluwa@gmail.com',
      linkedIn: 'Odumosu Olaoluwa ',
      instagram: 'ola_bata47',
      facebook: 'odumosu olaoluwa',
      twitter: 'odumosu olaoluwa ',
      position_held: '-',
      skills: '-',
      hobbies:
          'cooking, reading , watching movies , traveling ,playing football , listening to songs .',
      favorite_course: 'Family Law ',
      class_crush: '-',
      parting_words: 'God’s not Dead '),
  Students9(
      image: 'assets/students/111.jpg',
      name: 'Odunuga Josephine Moyosoluwa',
      nickname: 'Momo',
      dob: '3/5',
      state_of_origin: 'Ogun',
      mobile_number: 08108145169,
      email: 'Josedun139@gmail.com',
      linkedIn: '-',
      instagram: 'The_moyosoluwa',
      facebook: 'Moyo odunuga',
      twitter: 'dasfsf',
      position_held: 'dauhidad',
      skills: 'Cooking',
      hobbies: 'Reading',
      favorite_course: 'Women& the law',
      class_crush: 'Except money is a member of our class',
      parting_words:
          'I would like to thank absolutely nobody. I did this myself.'),
  Students9(
      image: 'assets/students/112.jpg',
      name: 'Ofor charles chigozie',
      nickname: 'Tiny',
      dob: '1/22',
      state_of_origin: 'Abia',
      mobile_number: 09030744626,
      email: 'Oforcharles97@gmail.com',
      linkedIn: '-',
      instagram: 'The5th__god',
      facebook: '-',
      twitter: '@daddy_buhari',
      position_held: '-',
      skills: 'Driving …Drawing',
      hobbies: 'Driving..Sports',
      favorite_course: 'Women and the law',
      class_crush: 'Rhoda',
      parting_words: 'The earlier the better'),
  Students9(
      image: 'assets/students/113.jpg',
      name: 'Ogbekhilu Faith',
      nickname: 'Esee',
      dob: '2/22',
      state_of_origin: 'Edo',
      mobile_number: 07059567150,
      email: 'fogbekhilu@gmail.com',
      linkedIn: '-',
      instagram: 'Esee_ohe',
      facebook: 'Faith Ogbekhilu',
      twitter: 'Ogbekhilu Faith (Esee_ohe)',
      position_held: '-',
      skills:
          'Concentrate on what you do well, and do it better than anyone else',
      hobbies: 'Playing games e.g.Ludo,cards, Scrabble e.t.c',
      favorite_course: 'Women and the law',
      class_crush: 'B.',
      parting_words: 'The downfall of a man is not the end of the world'),
  Students9(
      image: 'assets/students/114.jpg',
      name: 'Ogunade Oluwadamilola Adedayo ',
      nickname: 'Amoluade ',
      dob: '7/30',
      state_of_origin: 'Ogun',
      mobile_number: 08168420107,
      email: 'Damilolaogunade@gmail.com ',
      linkedIn: '-',
      instagram: 'amoluade_',
      facebook: '-',
      twitter: '@amoluade ',
      position_held: '-',
      skills: 'How to survive no matter the odds.',
      hobbies: 'Making the world a better place in my own way ',
      favorite_course: 'Women and the law ',
      class_crush: '-',
      parting_words: 'You only live once.'),
];
