// ignore_for_file: non_constant_identifier_names

class Students2 {
  String image;
  String name;
  String nickname;
  String dob;
  String state_of_origin;
  int mobile_number;
  String email;
  String linkedIn;
  String instagram;
  String facebook;
  String twitter;
  String position_held;
  String skills;
  String hobbies;
  String favorite_course;
  String class_crush;
  String parting_words;

  Students2(
      {required this.image,
      required this.name,
      required this.nickname,
      required this.dob,
      required this.state_of_origin,
      required this.mobile_number,
      required this.email,
      required this.linkedIn,
      required this.instagram,
      required this.facebook,
      required this.twitter,
      required this.position_held,
      required this.skills,
      required this.hobbies,
      required this.favorite_course,
      required this.class_crush,
      required this.parting_words});
}

List<Students2> studentList2 = [
  Students2(
      image: 'assets/students/25.jpg',
      name: 'Adeyemi Titilayo Rhoda',
      nickname: '-',
      dob: '7/26',
      state_of_origin: 'Osun',
      mobile_number: 08185701303,
      email: 'adeyemittl@gmail.com',
      linkedIn: '-',
      instagram: 'Rhohdar ',
      facebook: '-',
      twitter: 'Rhohdar ',
      position_held: 'Face of law, Social Secretary',
      skills: 'Hair making',
      hobbies: 'Working out, sporting activities in general',
      favorite_course: 'Women and the law',
      class_crush: 'Myself',
      parting_words: 'May we all find our successful paths'),
  Students2(
      image: 'assets/students/26.jpg',
      name: 'Agbaje Oluwagbemisola Ireyinka',
      nickname: 'Yinkus',
      dob: '6/6',
      state_of_origin: 'Ondo',
      mobile_number: 08168426792,
      email: 'agbajeoluwagbemisola@gmail.com',
      linkedIn: 'Agbaje Oluwagbemisola',
      instagram: 'agbaje_Oluwagbemisola or yinkus_vogue',
      facebook: 'Agbaje Oluwagbemisola',
      twitter: 'Agbaje Oluwagbemisola',
      position_held:
          'Financial Secretary, Head of Ushering Ministry, General Secretary',
      skills: 'Fashion Designing',
      hobbies:
          'Listening to music, surfing the internet, learning new things. ',
      favorite_course: 'Family Law',
      class_crush: '-',
      parting_words: 'Meet you all at the top🤗'),
  Students2(
      image: 'assets/students/27.jpg',
      name: 'Ajide Ibukunoluwa Faith',
      nickname: 'IBK',
      dob: '5/14',
      state_of_origin: 'Lagos',
      mobile_number: 08171319134,
      email: 'Ajideibukun2001@gmail.com',
      linkedIn: '-',
      instagram: 'Hiibeekhay',
      facebook: 'Ajide Ibukun',
      twitter: 'Hibeekhayy',
      position_held: '-',
      skills: 'Writing and Baking',
      hobbies: 'Reading books, watching movies',
      favorite_course: 'Women and the Law',
      class_crush: 'Salami Abolanle ',
      parting_words: 'Bella Ciao!!'),
  /*Students2(
      image: 'assets/students/28.jpg',
      name: 'Ajose Esther Adenike',
      nickname: '-',
      dob: '7/30',
      state_of_origin: 'Ogun',
      mobile_number: 09070694533,
      email: 'ajoseestheradenike@gmail.com',
      linkedIn: '-',
      instagram: 'evolet_nike',
      facebook: 'Ajose Esther Adenike',
      twitter: '-',
      position_held:
          'President - Anointing Youth Fellowship (RCCG Ogun9) 2019-2021',
      skills: '-',
      hobbies: 'Day dreaming',
      favorite_course: 'Family Law',
      class_crush: '-',
      parting_words:
          'There\'s so much to learn out there beyond the grammar and nobility that accompanies the law profession. So, do your best to find out what\'s in life for you and what\'s in you for life.')*/
  Students2(
      image: 'assets/students/29.jpg',
      name: 'Akan-an Adesodun Janet',
      nickname: 'Dessy',
      dob: '12/19',
      state_of_origin: 'Ogun',
      mobile_number: 07010041585,
      email: 'akananadesodun@gmail.com',
      linkedIn: 'Akan-an Adesodun',
      instagram: 'dessy_sparkles',
      facebook: 'Akan-an Adesodun',
      twitter: '-',
      position_held: '-',
      skills: 'Hairdressing',
      hobbies: 'Traveling,Reading and writing',
      favorite_course: 'Land law',
      class_crush: 'Adesodun',
      parting_words:
          'It has been an awesome experience with the LEGAL ACHIEVERS, all the dramas and the love. See you all at the top.'),
  Students2(
      image: 'assets/students/30.jpg',
      name: 'Akano Victor Oluwatomi',
      nickname: 'Veestix',
      dob: '12/27',
      state_of_origin: 'Oyo',
      mobile_number: 09067028111,
      email: 'akanovictor79@gmail.com',
      linkedIn: '-',
      instagram: 'Veestix79',
      facebook: 'Akano Victor Oluwatomi',
      twitter: 'Veestix79',
      position_held: '-',
      skills: 'Music',
      hobbies: 'Singing',
      favorite_course: 'Intellectual property',
      class_crush: 'Feyintola Peace',
      parting_words:
          'You can never please humans just keep doing what is right'),
  Students2(
      image: 'assets/students/31.jpg',
      name: 'Akin oyekan Love',
      nickname: '-',
      dob: '8/13',
      state_of_origin: 'Ogun',
      mobile_number: 09033800718,
      email: 'Ifetaiwo17@gmail.com',
      linkedIn: 'Akinoyekan Love',
      instagram: 'Akinoyekan20',
      facebook: 'Akinoyekan Ifeoluwa',
      twitter: '-',
      position_held: '-',
      skills: 'Baking',
      hobbies: 'Cooking and trying out new things',
      favorite_course: 'Law of tort and family law',
      class_crush: '-',
      parting_words:
          'You can do all things through the strength of Christ. Therefore lean not on your own understanding.'),
  Students2(
      image: 'assets/students/32.jpg',
      name: 'Akinbami Aminat',
      nickname: 'Meenahkimbs',
      dob: '7/12',
      state_of_origin: 'Ogun',
      mobile_number: 07067466222,
      email: 'biolakimbs@gmail.com',
      linkedIn: '-',
      instagram: 'Ahmean_ah',
      facebook: 'Aminah Akinbami',
      twitter: 'Meenahkimbs1',
      position_held: 'Assistant coordinator 300l NAMLAS.',
      skills: 'Cooking',
      hobbies: 'Talking,Dancing, Reading',
      favorite_course: 'Women and the Law',
      class_crush: '-',
      parting_words: 'One love keeps us together.'),
  Students2(
      image: 'assets/students/34.jpg',
      name: 'Akinde Oluwasegun Emmanuel ',
      nickname: '-',
      dob: '2/9',
      state_of_origin: 'Ogun',
      mobile_number: 08144581677,
      email: 'akindeemuel@gmail.com',
      linkedIn: 'Akinde Oluwasegun',
      instagram: 'Akindesegx',
      facebook: 'Segun Akinde ',
      twitter: 'Oluwasegun Akinde',
      position_held: '-',
      skills: '-',
      hobbies: 'Surfing net and watching dancers',
      favorite_course: 'Company law',
      class_crush: 'Akinde Oluwasegun',
      parting_words: 'Be at peace with all men'),
  Students2(
      image: 'assets/students/35.jpg',
      name: 'Akindele-oscar olorunyomi ',
      nickname: '-',
      dob: '1/27',
      state_of_origin: 'jssjss',
      mobile_number: 09086753336,
      email: 'olorunyomip27@gmail.com',
      linkedIn: 'Olorunyomi Akindele-Oscar',
      instagram: '@Olorunyomi Akindele-Oscar',
      facebook: 'Olorunyomi Akindele-Oscar',
      twitter: '-',
      position_held: '-',
      skills: 'bsjfs',
      hobbies: 'Reading and watching movies ',
      favorite_course: 'Landlaw',
      class_crush: '-',
      parting_words: '-'),
  Students2(
      image: 'assets/students/36.jpg',
      name: 'Akinniyi Adeniyi Oluwadamilare',
      nickname: 'Neyo Of Law.',
      dob: '4/12',
      state_of_origin: 'Ogun',
      mobile_number: 08161816347,
      email: 'neyooflaw@gmail.com',
      linkedIn: 'Akinniyi Adeniyi',
      instagram: 'Niyifamous',
      facebook: 'Akinniyi Adeniyi Oluwadamilare',
      twitter: 'Akinniyi Adeniyi (Neyo of law)',
      position_held:
          'Honourable member of Law Students Society and Constituency Leader 18/19.\nDirector Of Legal Affairs , National Association Of University Students ,Ogun CMC (NAUS)\nAppointment as the : Director of campus  projects  , information and implementation ,OOUSUG\'21',
      skills:
          'Leadership skills , Public affairs analyst , Pro - democracy Activist. ',
      hobbies:
          'Listening to news , Politics, Sports , Intellectual Discussions ,etc. ',
      favorite_course:
          'Constitutional Law , Family Law and Gender and the law.',
      class_crush: '-',
      parting_words:
          'To all my colleagues : Go into the World and do well But most importantly go into the World and do good. Also , let\'s follow our passion it will lead us to our  purposes. We shall all meet at the Apogee by God\'s grace. Amen. '),
  Students2(
      image: 'assets/students/37.jpg',
      name: 'Akinyelu Mary Oluwafunmilayo',
      nickname: 'Adunni, Dodos, This_Egungirl.',
      dob: '5/10',
      state_of_origin: 'Osun',
      mobile_number: 08124273490,
      email: 'akinyelumary@gmail.com',
      linkedIn: 'HAIRAFFAIRS',
      instagram: 'This_Egun_girl',
      facebook: 'Akinyelu Mary',
      twitter: '-',
      position_held: 'Religious',
      skills: 'Baking',
      hobbies:
          'Anything that caught my fancy, Anything that doesn\'t stress me.',
      favorite_course: 'Women and the law',
      class_crush: 'Eniola',
      parting_words: '-'),
  Students2(
      image: 'assets/students/38.jpg',
      name: 'Akinyemi Qudus Ayomide ',
      nickname: '-',
      dob: '7/9',
      state_of_origin: 'Ogun',
      mobile_number: 07051095641,
      email: 'akinyemianuolu@gmail.com',
      linkedIn: 'Anuolu Grace',
      instagram: 'hermazin_grace',
      facebook: 'Anuola Gracie',
      twitter: 'AkinyemiAnuola5',
      position_held:
          'Chancellor ,Legal Magnate and Company (2017) Secretary , Apostolic Faith Campus Fellowship ( June 2018- June 2019, Feb 2021- Nov 2021)',
      skills: 'Internet Marketing, Copywriting (Creating Sales Copy) ',
      hobbies:
          'Learning new things. Sewing clothes. Reading books at my leisure time Making money.',
      favorite_course: 'Law of Tort, Family law',
      class_crush: '-',
      parting_words:
          '“Knock Knock” “Who’s there?” “I’m” “I’m Who?” “I’m Out!”'),
  Students2(
      image: 'assets/students/39.jpg',
      name: 'Akinyemi Qudus Ayomide ',
      nickname: '-',
      dob: '7/8',
      state_of_origin: 'Ogun',
      mobile_number: 07051095641,
      email: 'qudusakinyemi8@gmail.com',
      linkedIn: '-',
      instagram: '@yvessaintladen',
      facebook: '-',
      twitter: '@yvessaintouki',
      position_held: '-',
      skills: '-',
      hobbies: 'Vibing',
      favorite_course: 'Petroleum and Energy law',
      class_crush: '-',
      parting_words: '-'),
  Students2(
      image: 'assets/students/40.jpg',
      name: 'Akiode Eunice Olufunke',
      nickname: 'Eunice',
      dob: '2/28',
      state_of_origin: 'Ogun',
      mobile_number: 08083124145,
      email: 'eunicearklor1@gmail.com',
      linkedIn: '-',
      instagram: 'n_eece',
      facebook: 'Akiode Eunice Olufunke',
      twitter: 'Yu_yuua',
      position_held: '-',
      skills: 'Tailoring',
      hobbies: 'Singing and reading',
      favorite_course: 'Criminal law',
      class_crush: 'Feranmi',
      parting_words:
          'It\'s being an amazing journey. All the glory to God who makes all things beautiful in his own time.'),
  Students2(
      image: 'assets/students/41.jpg',
      name: 'Alabi Aishat Mogbonjubola ',
      nickname: 'A’ish',
      dob: '3/3',
      state_of_origin: 'Ogun ',
      mobile_number: 08108476245,
      email: 'aishatjubola@gmail.com',
      linkedIn: 'Alabi Aishat Mogbonjubola ',
      instagram: 'aishatmogbonjubola',
      facebook: '-',
      twitter: '-',
      position_held:
          '" Namlas Coordinator General Member of LSPC,500l constituency leader"',
      skills: 'I learnt to be always optimistic 😊',
      hobbies: 'Taking pictures,eating and going out',
      favorite_course: 'Land law',
      class_crush: '-',
      parting_words:
          'Instruction ends in the four walls of classroom but education ends only with life'),
  Students2(
      image: 'assets/students/42.jpg',
      name: 'Alabi Esther Odunayo',
      nickname: '-',
      dob: '2/1',
      state_of_origin: 'Osun',
      mobile_number: 08101114688,
      email: 'alabiesther95@gmail.com',
      linkedIn: 'Alabi Esther',
      instagram: '-',
      facebook: 'Alabi Esther Fiyin',
      twitter: '-',
      position_held: '-',
      skills: '-',
      hobbies: 'Reading',
      favorite_course: '-',
      class_crush: '-',
      parting_words: 'Focus'),
  Students2(
      image: 'assets/students/46.jpg',
      name: 'Alagbala Oluwamayokun',
      nickname: 'Mayor, miji',
      dob: '1/6',
      state_of_origin: 'Ogun',
      mobile_number: 08189625116,
      email: 'alagbalamayokunabbeyccc@gmail.com',
      linkedIn: '-',
      instagram: 'fikunmy_',
      facebook: 'Alagbala Ola',
      twitter: '6th Bella',
      position_held: 'Clasfon Class Pastor in 2018/2019',
      skills: '-',
      hobbies: 'Reading, having group discussion,cooking',
      favorite_course:
          'I love any course that had to do with land...so I\'ll say land law/ conveyance has my heart',
      class_crush: 'Owolabi Timilehin Samuel',
      parting_words: 'Put God first, do you best and leave the rest!'),
  Students2(
      image: 'assets/students/48.jpg',
      name: 'Anjorin Oluwafunke Oluwaseyi ',
      nickname: '-',
      dob: '4/2',
      state_of_origin: 'Ogun',
      mobile_number: 08130136549,
      email: 'anjorinmarcella@gmail.com',
      linkedIn: '-',
      instagram: '@marc.ella__',
      facebook: '-',
      twitter: '-',
      position_held:
          'President, Nigeria Federation of Catholic Students (NFCS)',
      skills: '-',
      hobbies: '-',
      favorite_course: 'Intellectual property',
      class_crush: '-',
      parting_words: '-'),
  Students2(
      image: 'assets/students/49.jpg',
      name: 'Anubami Victoria Olokode',
      nickname: 'VicBam',
      dob: '4/9',
      state_of_origin: 'Ogun',
      mobile_number: 08104445737,
      email: 'vicanubami@gmail.com',
      linkedIn: 'Olokode Anubami',
      instagram: '@vicbamfashions',
      facebook: 'Olokode Anubami',
      twitter: '-',
      position_held:
          'McfOou Organizing Secretary, JBsummit Assistant Organizing Secretary 2',
      skills: 'Organization',
      hobbies: 'Reading, window-shopping, sleeping.',
      favorite_course: 'Family Law',
      class_crush: 'Pastor David',
      parting_words: 'Keep being you and never give up on yourself.'),
];
