// ignore_for_file: non_constant_identifier_names

class Students11 {
  String image;
  String name;
  String nickname;
  String dob;
  String state_of_origin;
  int mobile_number;
  String email;
  String linkedIn;
  String instagram;
  String facebook;
  String twitter;
  String position_held;
  String skills;
  String hobbies;
  String favorite_course;
  String class_crush;
  String parting_words;

  Students11(
      {required this.image,
      required this.name,
      required this.nickname,
      required this.dob,
      required this.state_of_origin,
      required this.mobile_number,
      required this.email,
      required this.linkedIn,
      required this.instagram,
      required this.facebook,
      required this.twitter,
      required this.position_held,
      required this.skills,
      required this.hobbies,
      required this.favorite_course,
      required this.class_crush,
      required this.parting_words});
}

List<Students11> studentList11 = [
  Students11(
      image: 'assets/students/130.jpg',
      name: 'Okubule eniola oyetunde ',
      nickname: 'Eniola ',
      dob: '1/21',
      state_of_origin: 'Ogun',
      mobile_number: 09095321471,
      email: 'eniolafrancis2000@gmail.com',
      linkedIn: '-',
      instagram: '-',
      facebook: 'Eniola francis',
      twitter: '-',
      position_held: '-',
      skills: 'Content creation.',
      hobbies: 'Cooking, writing and listening to music.',
      favorite_course: 'Land law',
      class_crush: 'Oreoluwa ',
      parting_words: 'Consistency is key to success. We meet at the top!'),
  Students11(
      image: 'assets/students/132.jpg',
      name: 'Okunowo Olorunfunmi Faith ',
      nickname: '-',
      dob: '2/15',
      state_of_origin: 'Ogun',
      mobile_number: 09086332535,
      email: 'Faithfunmi6@gmail.com',
      linkedIn: '-',
      instagram: 'Olorunfunmi_xx',
      facebook: 'Funmi Okunowo ',
      twitter: '-',
      position_held: '-',
      skills: '-',
      hobbies: 'Sketching, cooking, disturbing',
      favorite_course: 'Sociology ',
      class_crush: '-',
      parting_words: 'Work smart, not hard.'),
  Students11(
      image: 'assets/students/134.jpg',
      name: 'Oladipupo Temiloluwa',
      nickname: 'Observer ',
      dob: '4/15',
      state_of_origin: 'Lagos ',
      mobile_number: 07011204415,
      email: 'Temidawizzy@gmail.com',
      linkedIn: '-',
      instagram: 'Temidagreat',
      facebook: '-',
      twitter: '-',
      position_held: '-',
      skills: '-',
      hobbies: 'Making money ',
      favorite_course: 'Women and the law',
      class_crush: '-',
      parting_words: 'Don\'t try'),
  Students11(
      image: 'assets/students/135.jpg',
      name: 'Olaifa Mufutau Olawuyi',
      nickname: 'Sen. Fops',
      dob: '10/31',
      state_of_origin: 'Ogun',
      mobile_number: 08162102446,
      email: 'mufutauolaifa@gmail.com',
      linkedIn: 'Olaifa Mufutau',
      instagram: 'Olaifa Mufutau Olawuyi(wuyi_gram)',
      facebook: 'Olaifa Mufutau Olanrewaju',
      twitter: 'Olaifa Olawuyi (Ajasco papa)',
      position_held:
          '"Senator 19/20 & 20/21 academic session Member OOU-SUG Welfare Committee 19/20 session NAMLAS Chief Logistics Officer Law Clinic (Member, Projects and Logistics Dept.) Faculty Committee Logistics Officer Member, SUG Constitutional Review Committee"',
      skills:
          '"Shoe branding and sales(making and marketing) Digital Marketing Website development (wordpress/front end) Python(beginner) Graphics design "',
      hobbies: 'Traveling/Tourism',
      favorite_course: '-',
      class_crush:
          '"Salu Azeezat Yossy baby All the fair ladies with backside and baby food🥺"',
      parting_words:
          '"The goal has never been and can never be to hold an office forever, but to implement changes that will stand the test of time. Hence, whenever we find ourselves in any capacity either by way of appointment or election, access yourself whether you are the \'Model Nigerian Youth\' ripe for modern governance or you\'re towing the path of the modern slave masters by learning the old tricks that ruined Nigeria."'),
  Students11(
      image: 'assets/students/137.jpg',
      name: 'Olajide Oluwadaralayemi Rhoda',
      nickname: '-',
      dob: '5/11',
      state_of_origin: 'Ogun',
      mobile_number: 08161715582,
      email: 'daraaolajide@gmail.com',
      linkedIn: '-',
      instagram: '_daralayemi',
      facebook: '-',
      twitter: '_daralayemi',
      position_held: '-',
      skills: 'Talking, sometimes writing',
      hobbies: 'Having fun',
      favorite_course: 'Family law',
      class_crush: '-',
      parting_words: 'Never fail yourself by being someone you’re not'),
  Students11(
      image: 'assets/students/138.jpg',
      name: 'Olaleru Peace Eniola',
      nickname: '-',
      dob: '2/22',
      state_of_origin: 'Kwara',
      mobile_number: 08169825062,
      email: 'Peaceolaleru@gmail.com',
      linkedIn: 'Olaleru Peace@ Linkedin',
      instagram: 'shalom-piz@IG',
      facebook: 'Olalerupeace@facebook',
      twitter: 'Olalerupeace@twitter',
      position_held: '-',
      skills: '-',
      hobbies: 'Reading',
      favorite_course: 'Women and the Law',
      class_crush: 'Me me me',
      parting_words: '-'),
  Students11(
      image: 'assets/students/142.jpg',
      name: 'Olawore Godwin Akanbi',
      nickname: 'Gwin',
      dob: '9/30',
      state_of_origin: 'Ogun',
      mobile_number: 07068628956,
      email: 'Olaworegodwin66@gmail.com',
      linkedIn: '-',
      instagram: '-',
      facebook: '-',
      twitter: '-',
      position_held: '-',
      skills: '-',
      hobbies: 'Music, sports',
      favorite_course: 'Criminal law',
      class_crush: '-',
      parting_words: '-'),
  Students11(
      image: 'assets/students/143.jpg',
      name: 'Olubode David Oluwaseun',
      nickname: 'Dheyvhed',
      dob: '5/9',
      state_of_origin: 'Ogun',
      mobile_number: 07037322088,
      email: 'doolubode@gmail.com',
      linkedIn: '-',
      instagram: '@dheyvhed',
      facebook: 'David Olubode',
      twitter: '@dheyvhed',
      position_held: '-',
      skills: '-',
      hobbies: 'Playing game',
      favorite_course: 'Land law',
      class_crush: '-',
      parting_words:
          'I appreciate the fact that we met, and parting with joy. I strongly believe I\'ll see you at the top!'),
  Students11(
      image: 'assets/students/144.jpg',
      name: 'Olukoya Oyinlola Olufunke',
      nickname: 'Sisi Oyin',
      dob: '11/12',
      state_of_origin: 'Ogun',
      mobile_number: 08162898753,
      email: 'Olukoyaoyin@gmail.com',
      linkedIn: '-',
      instagram: 'Sisi Oyin',
      facebook: '-',
      twitter: 'Sisi Oyin',
      position_held: '-',
      skills: '-',
      hobbies:
          'Watching movies/ reading books except school books of course 😒',
      favorite_course: 'Family law',
      class_crush: '-',
      parting_words:
          'Thank you all for the beautiful experience and I wish everyone success in the future endeavors '),
  Students11(
      image: 'assets/students/145.jpg',
      name: 'Oluleye Sijibomi Ayomide',
      nickname: 'gnikkcalb',
      dob: '3/7',
      state_of_origin: 'Ondo',
      mobile_number: 08142343781,
      email: 'olusiji29@gmail.com',
      linkedIn: '-',
      instagram: '-',
      facebook: '-',
      twitter: '@gnikkcalB',
      position_held: '-',
      skills: '-',
      hobbies: 'Writing',
      favorite_course: 'Petroleum law',
      class_crush: 'I kept it Halal',
      parting_words: 'Just find a way'),
];
