// ignore_for_file: non_constant_identifier_names

class Students17 {
  String image;
  String name;
  String nickname;
  String dob;
  String state_of_origin;
  int mobile_number;
  String email;
  String linkedIn;
  String instagram;
  String facebook;
  String twitter;
  String position_held;
  String skills;
  String hobbies;
  String favorite_course;
  String class_crush;
  String parting_words;

  Students17(
      {required this.image,
      required this.name,
      required this.nickname,
      required this.dob,
      required this.state_of_origin,
      required this.mobile_number,
      required this.email,
      required this.linkedIn,
      required this.instagram,
      required this.facebook,
      required this.twitter,
      required this.position_held,
      required this.skills,
      required this.hobbies,
      required this.favorite_course,
      required this.class_crush,
      required this.parting_words});
}

List<Students17> studentList17 = [
  Students17(
      image: 'assets/students/52.jpg',
      name: 'Odusote Fawaz Adedeji',
      nickname: '-',
      dob: '7/9',
      state_of_origin: 'Ogun',
      mobile_number: 09078270370,
      email: 'odusotefawaz@gmail.com ',
      linkedIn: '-',
      instagram: '-',
      facebook: 'Odusote Fawaz Adedeji',
      twitter: '-',
      position_held: '-',
      skills: '-',
      hobbies: 'Reading ',
      favorite_course: 'Commercial Law',
      class_crush: 'Self',
      parting_words: '-'),
  Students17(
      image: 'assets/students/53.jpg',
      name: 'Abogunrin Oluseye Temilorun',
      nickname: 'T. Minor',
      dob: '5/2',
      state_of_origin: 'Ogun',
      mobile_number: 08125603515,
      email: 'abogunrinseye@gmail.com',
      linkedIn: 'OLUSEYE TEMILORUN ABOGUNRIN',
      instagram: 'Seye_abogunrin',
      facebook: 'Abogunrin Temilorun Oluseye',
      twitter: 'Seye_abogunrin',
      position_held: 'President, Intellectual Property Law Club OOU',
      skills: 'Certified Mediator, Team Work and Personal Proficiency',
      hobbies: 'Music(guitar, Vocal Coaching), Graphics Designs, ',
      favorite_course: 'Intellectual Property Law',
      class_crush: 'Odunayo Ibitoye ',
      parting_words:
          'Meeting everyone has been nothing short of a blessing. I have learnt from all! I wish everyone of us good and Godly Success. I will miss you all Class🥺 You are all part of the story of my life © Temilorun (T.Minor)'),
  Students17(
      image: 'assets/students/77.jpg',
      name: 'Ajayi oluwamayowa Opemipo',
      nickname: 'Mayor-legacy',
      dob: '12/28',
      state_of_origin: 'Ekiti',
      mobile_number: 08145111553,
      email: 'Opemayowa96@gmail.com ',
      linkedIn: '-',
      instagram: '-',
      facebook: 'Ade-Ajayi oluwamayowa ',
      twitter: '-',
      position_held:
          'General legal counsel @ Junior chambere international,  Public relations officer @ Christian law students society ',
      skills: 'Administrative skills',
      hobbies: 'Reading',
      favorite_course: 'Jurisprudence ',
      class_crush: '-',
      parting_words: '-'),
  Students17(
      image: 'assets/students/93.jpg',
      name: 'Ogochukwu Ernest Sunday',
      nickname: 'Pureheart',
      dob: '5/5',
      state_of_origin: 'Ebonyi',
      mobile_number: 07031863218,
      email: 'Houseofphame@gmail.com',
      linkedIn: '-',
      instagram: '-',
      facebook: '-',
      twitter: '-',
      position_held: '-',
      skills: '-',
      hobbies: 'Sing, Writing Poems',
      favorite_course: 'Land Law',
      class_crush: 'SOS',
      parting_words: '-'),
  Students17(
      image: 'assets/students/131.jpg',
      name: 'Okunola Oyindamola Aishat',
      nickname: 'Oyinda',
      dob: '7/16',
      state_of_origin: 'Ogun',
      mobile_number: 09099457403,
      email: 'oyindamolaaishat1679@gmail.com',
      linkedIn: '-',
      instagram: '-',
      facebook: 'Okunola Oyindamola Busayo',
      twitter: '@OyindamolaAO',
      position_held: '-',
      skills: 'Legal Writing and Drafting',
      hobbies: 'Listening to music, Acting drama',
      favorite_course:
          'Criminology (most of the topics were relatable and easy to understand)',
      class_crush: 'Nobody',
      parting_words: 'Be kind to all men for what goes around comes around'),
  Students17(
      image: 'assets/students/98.jpg',
      name: 'Olatunji Folaranmi Solomon ',
      nickname: 'Troy_z Mula',
      dob: '9/13',
      state_of_origin: 'Oyo',
      mobile_number: 08087977210,
      email: 'troy_zmoola@rocketmail.com',
      linkedIn: 'troy_zmula',
      instagram: 'Troyz Mula',
      facebook: 'troy_zmula',
      twitter: '-',
      position_held: '-',
      skills: '-',
      hobbies: 'Watching Football, Reading Journals ',
      favorite_course: 'Criminology',
      class_crush: 'Titilayo',
      parting_words: '-'),
  Students17(
      image: 'assets/students/105.jpg',
      name: 'Abisoye Onajinrin ',
      nickname: 'Abijah',
      dob: '3/26',
      state_of_origin: 'Ogun',
      mobile_number: 08183988392,
      email: 'abijahonajinrin@gmail.com ',
      linkedIn: 'Abisoye Onajinrin',
      instagram: '_abijah_',
      facebook: 'Abisoye Onajinrin ',
      twitter: '-',
      position_held:
          'Scribe Inner Temple OOU, Evangelism/Prayer Secretary CLASFON OOU',
      skills: 'Public Speaking Customer Relations Strategic Planning ',
      hobbies: 'Travelling, Networking',
      favorite_course: 'Criminology',
      class_crush: '-',
      parting_words:
          'Know thyself : And to this Knowledge : Be True. I love everyone deeply'),
  Students17(
      image: 'assets/students/115.jpg',
      name: 'Ogundeji Mariam Yewande ',
      nickname: 'Ashira',
      dob: '5/15',
      state_of_origin: 'Ogun',
      mobile_number: 08150670709,
      email: 'wandeogundeji23@gmail.com',
      linkedIn: '-',
      instagram: '_yewandeogundeji',
      facebook: 'Wande Ogundeji',
      twitter: '-',
      position_held: '-',
      skills: 'I\'m good at swimming ,writing poems etc.',
      hobbies: 'Swimming ,sketching , reading , relaxation.',
      favorite_course: 'My best course is Land law.',
      class_crush: '-',
      parting_words: 'I will miss O.O.U faculty of law.'),
  Students17(
      image: 'assets/students/125.jpg',
      name: 'Oguntomi Olorunfemi Samuel',
      nickname: 'Samfamo; Saint',
      dob: '9/29',
      state_of_origin: 'Ogun',
      mobile_number: 07062506318,
      email: 'olorunfemi.oguntomi@gmail.com',
      linkedIn: '-',
      instagram: 'I_am_Samfamo',
      facebook: '-',
      twitter: 'Samfamo',
      position_held: 'Saintship',
      skills: 'Acting; ',
      hobbies: 'Talking, Comedy, Football',
      favorite_course: 'Women&The Law',
      class_crush: 'Tiwalade',
      parting_words: 'Insert Witty Saying'),
  Students17(
      image: 'assets/students/54.jpg',
      name: 'Awosanya .M. Olamide',
      nickname: 'Olly',
      dob: '6/1',
      state_of_origin: 'Lagos',
      mobile_number: 08126132584,
      email: 'adunolamide453@gmail.com',
      linkedIn: 'Olamide Awosanya',
      instagram: 'sattis_delish',
      facebook: 'adun_ola',
      twitter: 'adun_ola',
      position_held: 'HOG Street laws and community service OOU law clinc',
      skills: 'group work and excellent team spirit ',
      hobbies: 'Singing,gisting,reading etc',
      favorite_course: 'Land law&family law',
      class_crush: '-',
      parting_words: 'Thanks for being an amazing family'),
];
