class Poem {
  String title;
  String content;

  Poem({required this.title, required this.content});
}

List<Poem> poemList = [
  Poem(
      title: 'The 19-Year-Old Rant',
      content:
          'Why are you so bothered?\nI don\'t want to live,\nWhat do you mean? What caused that?\nIt\'s the life you made me live.\nLook, this is all deception,\nThe devil\'s in your head,\nHe\'s giving you tons of negative thoughts\nGet them out of your head,\nOn the contrary,\nI wouldn\'t bother taking my head off,\nShut up!\nOh wait,  can i take your head off?\nThis murderous tendency is growing,\nYou always feed it,\nIt seems like killing you,\nIs the only way to kill it,\nAre you okay?\nDon\'t you realise who you\'re talking to?\nI\'m not sure I\'m fine,\nBut I\'m sure you don\'t know who you\'re talking to,\nIf you looked into my thoughts,\nThey would scare you,\nSaying these things the way they are,\nIs the only way to spare you,\nI see what\'s going on here,\nYou have been possessed,\nI hope that\'s what\'s happening,\nSo that I can be delivered,\nBut not by you,\nYou don\'t have the required capacity,\nAs far as spirits are concerned,\nYou are not a valid entity\nWhat are you talking about?\nI\'m an ordained minister,\nYou don\'t have an ordained life,\nSo there\'s no life when you minister,\nSo you lead a congregation,\nBut you couldn\'t lead me to Christ,\nMany arrows point from you,\nBut none of them point to Christ,\nIf this is Christianity,\nTrust me, it\'s pointless,\nThis life you claim to have In Christ,\nIs actually lifeless,\nYou\'re a corpse,\nIt\'s no wonder there\'s a stench around you,\nYou don\'t know Jesus,\nThere\'s nothing like him in you,\nI would weep for joy, When I feel his presence,\nRight now,\nI don\'t even feel that anger in your presence,\nYou\'ve lost ranking,\nYou\'ve lost the place that you once held,\nI gave birth to you,\nThat\'s one thing I wished you didn\'t do,\nAt least I wouldn\'t feel how I do, if I didn\'t exist,\nI can make a list,\nOf everything that makes me not want to live,\nAnd most of the top ten is from you, I believe,\nLet bygones be bygones,\nBut this one never left,\nThe bygone is now a bye gun,\nand I\'m not looking into theft,\nI\'m looking into ending you,\nAnd then facing what\'s left,\nYou must be drunk,\nThat\'s why you\'re considering all these stupid decisions,\nIn my view,  your marriage was probably a worse decision,\nAre you mad? That\'s the union that made you,\nMy point exactly,\nRemove that union,\nAnd there would be no 19 year old guy wishing to kill you,\nOkay,  I see that you\'re frustrated,\nBut things are not that bad,\nOh, it\'s actually much worse,\nI haven\'t mastered the art of expressing bad,\nYou\'re just ranting because you\'re young,\nMust wait till you become a dad,\nYeah, I\'ve been thinking,\nI might never become one,\nCastration is a possibility,\nA very high one,\nI made myself a promise,\nI would be a better one,\nAnd if it is impossible,\nThen I\'ll never become one.\n\n-ITP\n 25/4/2020'),
  Poem(
      title: 'Crush Talk',
      content:
          'Look at me,\nI\'m right here,\nI brought myself to you,\nLove and care is what you want,\nBrought them both for you,\nLook into my eyes,\nYou can see how I feel,\nI can\'t hold my emotions,\nbut I know they are real,\nIf I say I don\'t like you,\nI would just be lying,\nIf I said your beauty doesn\'t stun me,\nI would just be lying,\nBut I want something eternal,\nSomething that lasts forever,\nWhen the pleasure never ends,\nIntimacy forever,\nHow can you desire that?\nYou\'re aware you are mortal,\nYou won\'t live forever,\nThis chance is your best offer,\nI\'ve thought about this proposal,\nHow long will you live?\nMaybe some eighty years,\nAt sixty, what will you have to give?\nIf your existence is limited to youth,\nIs it really worth the price?\nI want to want you in old age,\nBy then, will there still be beauty in your eyes?\nThat\'s why I\'m telling you this,\nWe don\'t have forever,\nWe\'ll be young for twenty more years,\nThirty years if we last longer,\nBut what happens after that?\nAll our passion fades away,\nAll the rush and excitement,\nThey didn\'t come to stay,\nSo we make the most of what we have,\nWe have fun while we can,\nI can be your lady,\nYou can be my man,\nLet\'s consider the strength,\nAll the rush and all the vigor,\nThe stamina to run for hours,\nThe pleasure in the figure,\nJust how much can we take,\nBefore our bodies start to ache,\nThere is more to the pleasure,\nThere are children we will make,\nI imagine it too,\nand it seems so glorious,\nBut what if we get wounded,\nPleasure Can be furious,\nYou desire me now,\nBut what if I\'m not satisfied?\nWhat if I\'m not that much,\nand you don\'t like my pride,\nWhat if my poses are unreasonable,\nand my angles are just crazy,\nWhat if I work too hard,\nand you can\'t call me baby,\nWhat if you hit your limit,\nBut I\'m still waiting for more,\nWhat if joy becomes pain,\nand the pleasure becomes gore,\nThere\'s so much more to this,\nThan the pleasure that it brings,\nSometimes there are chains,\nThat look like wedding rings,\nYour Shape defies Science,\nI\'m probably exaggerating,\nWhen I set my mind on you,\nThings begin gravitating,\nI once heard someone say,\nIf you like a flower, don\'t pluck it,\nThere\'s a smile on your face,\nI always want to remember it,\nYes, I like you,\nSo I actually want to have you,\nBut more so, I love you,\nSo let\'s be sure I\'m for you.\n\n- ITP\n(Iyanu The Poet).\n21-4-2020 '),
  Poem(
      title: 'What It Is',
      content:
          'You make me feel like I\'m trash,\nYou make me feel like I\'m worthless,\nYou make me wish for death,\nYou bring agony that\'s endless,\n\nWhen you speak of love,\nIt\'s clear you don\'t understand,\nWhat it is,\nThose guys said,\nIt is what it is,\n\nIt\'s like mathematics,\nYou think you\'re solving right,\nUntil you finish calculations,\nAnd your answer isn\'t right,\n\nTrust me when I tell you,\nYou\'ve miscalculated for years,\nYour miscalculations make me wish,\nI never saw those years,\n\nThink about stillborns,\nWhere do they go?\nDo they end up reborn?\nI might just want to know,\n\nBecause your presence makes my life not worth living,\nLet\'s hope I\'m drunk,\nAnd someday I\'ll wake up sober,\nAnd all this trash talk will be over,\n\nI\'m hoping,\nThat one day, I\'ll look back and truly smile,\nAnd see that everything you did,\nWas really worth the while,\n\nI hope I\'m happy to tell my kids about their grandparents,\nOr maybe I won\'t allow you become grandparents,\n\nRemember that joke you used to crack,\nAbout giving birth again,\nI never laughed,\nI can\'t imagine putting someone else through this pain,\n\nAnd if the cost is no marriage,\nI\'ll tell every crush goodbye,\nAnd if they want to know why I do it,\nI love you, that\'s why,\n\nI don\'t want to make investments,\nAnd hate the revenue,\nI don\'t want to continue a line of hate,\nI don\'t want to include you,\n\nIt\'s my act of kindness,\nLet me be the last infected one,\nAnd if there are 99 like this,\nThen I won\'t add another one,\n\nYou cant express love,\nIf you don\'t first define it,\nYou try to trace it from the earth,\nActually, you should divine it,\n\nPoison isn\'t food just because you think it is,\nYou were born in a prison, doesn\'t mean that\'s all there is,\n\nSometimes, I want to look at you\nWith pity and understand,\nBut these years have proved,\nYou\'ve not tried to learn more or understand,\n\nYou claim to have wisdom,\nFrom the many years you\'ve lived,\nBut the pain and the fury,\nSeems to be all that you received,\n\nYou have many rags,\nBut it\'s time to clothe the children,\nDid you go through all your pains,\nJust to pass it on to children?\n\nIt\'s weird calling you grown ups,\nIt\'s like you never grew,\nThe ability to reproduce,\nMight be all that you knew,\n\nThe idea of maturity,\nDoes not accompany age,\nYou can spend fifty years of your life,\nOn your first page,\n\nDo I claim to be wiser?\nI hope it\'s a lie,\nSo someday I can look back,\nAnd remember your words,\nAnd be happy that you spoke them,\nAnd write them on my walls,\n\nAnd when my children ask,\nDaddy, who said these things?\nI would tell them the words of the wisest among men,\nI hope that is the adjective,\nThat you carry by then.\n\n-ITP 2020. ')
];
